version: '3'
services:
  backend:
    image: razeencheng/ssltools_backend:${TAG}
    ports: 
      - "8080:8080"
    environment:
      - RUN_MODE=prod
    restart: always
  ssltools.tech:
    image: razeencheng/nginx_tls13:${NGINX_TAG}
    ports:
      - "443:443"
    volumes:
      - "./certs:/certs"
      - "./nginx/ssltools.tech.conf:/etc/nginx/conf.d/default.conf"
    links:
      - backend
